### ISSUE TITLE
Not a issue

### ISSUE THREAD

**Issue by yashilanka** [ThomasBurleson/angularjs-gsTimelines#4]
Hi this is not a issue reporting. i want to thank you to make this amazing library to happen. i'm searching and struggling to make that Meaningful Transition by my hand by using GSAP. but it fail when creating that kind of UI state changes for the multiple objects and i have trouble with the browser performance when i create that kind of effect for the multiple pages. so i think this is much better. and i also wonder if you can make jquery version and pure javascript version for this library and dedicated site and doc for this library. anyway. thank you very much. for your hard work.

**Comment by ThomasBurleson** [comment]
@yashilanka 

Thank you for your kind words.

The features of the gsTimeline DSL comes from both GSAP from **and** the amazing power of AngularJS Directives. It would be **very** difficult to create the equivalent features in jQuery since Directives with databinding and HTML compiling are not available.
